<Project>
  <Import Project="SharedConfiguration/Shared.props" />
  <PropertyGroup>
    <TargetSptVersion>4.0.3</TargetSptVersion>
    <Authors>SamSWAT, Arys, Tylevo</Authors>
    <Copyright>Copyright © SamSWAT, Arys 2025; Tylevo 2026</Copyright>
    <LangVersion>latest</LangVersion>
    <Configurations>Debug;SPT-3.10 Release;SPT-3.11 Release;SPT-4.0 Release;SPT-4.1 Release</Configurations>
    <SolutionName>Tylevo.HeliCrash</SolutionName>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <OutputPath>Build\Debug\</OutputPath>
    <TargetSptVersion>4.1.5</TargetSptVersion>
    <Optimize>false</Optimize>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <NoWarn>1701;1702;0649</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'SPT-3.10 Release' ">
    <OutputPath>Build\SPT-3.10\</OutputPath>
    <SptVersion>310x</SptVersion>
    <Optimize>true</Optimize>
    <NoWarn>1701;1702;0649</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'SPT-3.11 Release' ">
    <OutputPath>Build\SPT-3.11\</OutputPath>
    <SptVersion>311x</SptVersion>
    <Optimize>true</Optimize>
    <NoWarn>1701;1702;0649</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'SPT-4.0 Release' ">
    <OutputPath>Build\SPT-4.0\</OutputPath>
    <SptVersion>400x</SptVersion>
    <Optimize>true</Optimize>
    <NoWarn>1701;1702;0649</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'SPT-4.1 Release' ">
    <OutputPath>Build\SPT-4.1\</OutputPath>
    <SptVersion>415x</SptVersion>
    <TargetSptVersion>4.1.5</TargetSptVersion>
    <Optimize>true</Optimize>
    <NoWarn>1701;1702;0649</NoWarn>
  </PropertyGroup>
</Project>
